services:
  transcrib-apiv2:
    image: soavy/transcrib-api:v4
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - n8n_net

networks:
  n8n_net:
    external: true
